package fieldmind.research.app.util

import android.app.Application
import android.os.Build
import android.os.Process
import android.util.Log
import fieldmind.research.app.BuildConfig
import fieldmind.research.app.activities.FieldMindCrashActivity
import fieldmind.research.app.shared.data.model.AppSettings
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale
import java.util.concurrent.atomic.AtomicBoolean

object CrashReporter {

    private const val TAG = "CrashReporter"
    private val handlingCrash = AtomicBoolean(false)
    private var appSettings: AppSettings? = null
    private var previousHandler: Thread.UncaughtExceptionHandler? = null

    fun init(application: Application) {
        appSettings = runCatching { AppSettings.getInstance(application) }.getOrNull()
        previousHandler = Thread.getDefaultUncaughtExceptionHandler()

        Thread.setDefaultUncaughtExceptionHandler { thread, throwable ->
            if (isRuntimeShutdownThrowable(throwable)) {
                Log.w(TAG, "Ignoring uncaught exception during runtime shutdown on thread ${thread.name}")
                previousHandler?.uncaughtException(thread, throwable)
                return@setDefaultUncaughtExceptionHandler
            }

            if (!handlingCrash.compareAndSet(false, true)) {
                Log.e(TAG, "Recursive crash while handling previous crash", throwable)
                previousHandler?.uncaughtException(thread, throwable) ?: Process.killProcess(Process.myPid())
                return@setDefaultUncaughtExceptionHandler
            }

            val crashLog = buildCrashLog(thread, throwable)
            Log.e(TAG, "Uncaught exception on thread ${thread.name}: $crashLog")
            runCatching { appSettings?.addCrashLogEntry(crashLog) }
                .onFailure { Log.e(TAG, "Failed to persist crash log", it) }

            val launchedCrashScreen = runCatching {
                FieldMindCrashActivity.start(application.applicationContext, crashLog)
            }.onFailure { Log.e(TAG, "Failed to launch crash activity", it) }.isSuccess

            if (!launchedCrashScreen) {
                previousHandler?.uncaughtException(thread, throwable)
            }

            // The crash UI runs in :crash_process. Stop the corrupted app process after the
            // launch request has been handed to ActivityManager so the user is not left on a
            // half-rendered/blank task.
            Process.killProcess(Process.myPid())
            kotlin.system.exitProcess(10)
        }
    }

    fun buildCrashLog(thread: Thread, throwable: Throwable): String = buildString {
        appendLine("FieldMind Crash Report")
        appendLine("Generated: ${SimpleDateFormat("yyyy-MM-dd HH:mm:ss.SSS Z", Locale.US).format(Date())}")
        appendLine("Thread: ${thread.name} (id=${thread.id})")
        appendLine("Exception: ${throwable::class.java.name}")
        appendLine("Message: ${throwable.message ?: "—"}")
        appendLine("App: ${BuildConfig.APPLICATION_ID} ${BuildConfig.VERSION_NAME} (${BuildConfig.VERSION_CODE})")
        appendLine("Build: ${BuildConfig.BUILD_TYPE}")
        appendLine("Device: ${Build.MANUFACTURER} ${Build.MODEL}")
        appendLine("Android: ${Build.VERSION.RELEASE} (SDK ${Build.VERSION.SDK_INT})")
        appendLine()
        appendLine(Log.getStackTraceString(throwable))
    }

    private fun isRuntimeShutdownThrowable(throwable: Throwable?): Boolean {
        var cause = throwable
        while (cause != null) {
            val message = cause.message
            if (message != null && (
                    message.contains("Thread starting during runtime shutdown") ||
                        message.contains("Runtime shutdown in progress")
                    )
            ) {
                return true
            }
            cause = cause.cause
        }
        return false
    }

    fun recordNonFatal(throwable: Throwable, source: String = "unknown") {
        val crashLog = buildString {
            appendLine("Non-fatal error captured from: $source")
            append(Log.getStackTraceString(throwable))
        }
        Log.e(TAG, crashLog)
        if (::appSettings.isInitialized) {
            appSettings.addCrashLogEntry(crashLog)
        }
    }

    fun testCrash() {
        throw RuntimeException("This is a test crash generated by the app for demonstration purposes.")
    }
}
